### ISSUE TITLE
Number of deployed files

### ISSUE THREAD

**Issue by RussKie** [maraf/GitExtensions.PluginManager#28]
The manager contains 120 files.
I can't help but think that bundling of the manager with GE may be a challenge because of this.

Is there a reason for shipping netstandard.dll, System.\*.dll and Microsoft.\*.dll?
I can somewhat understand Nuget.*.dll, and even though I think they can be bundled up into a single assembly with ILMerge (e.g. like https://gist.github.com/thoemmi/3724333)

**Comment by maraf** [comment]
I used standard `dotnet publish` and than copied it all to zip file.
,NET Standard assemblies are there because UI independent projects target .NET Standard, but I'm sure they are redundant and can be removed.

Without these, it takes 20files. If it's still to much, I can try ILMerge, but I have never used it before..

**Comment by maraf** [comment]
`System.Net.Http` is required.

**Comment by maraf** [comment]
Without ILMerge, PluginManager consists of 21files.

**Comment by RussKie** [comment]
That's getting better 😊
Do you have any thoughts around deploying it?

**Comment by maraf** [comment]
I'm going to try ILMerge and than publish the patch.

**Comment by maraf** [comment]
Merged to a single exe file.
