### ISSUE TITLE
Plugin versioning and GE compatibility

### ISSUE THREAD

**Issue by maraf** [maraf/GitExtensions.PluginManager#36]
Right now I use these assumptions when pairing plugin version with GE version.

- All patch versions are backward compatible.
  - Example: Plugin written for GE-v3.1.0 should be compatible with GE-v3.1.*.

- Major and minor releases are in general considered not backward compatible.
  - Example: Plugin written for GE-v3.1.0 may not be compatible with GE-v3.2.\*, nor GE-v4.\*.*.
  - Plugin author should publish new version for each GE major and minor release.

This corresponds with plugin package dependency on `GitExtensions.Plugins` which is now typically defined as `[2.51,2.52)` and `[3.0,3.1)`.

@RussKie Is it correct according to your experiences with GE versions?

**Comment by RussKie** [comment]
> Major and minor releases are in general considered not backward compatible.

Dealing with dependencies in .NET world I use [semantic versioning](https://semver.org/), that prescribes that only change to the `major` version number is considered a breaking change.

What it means in GE context I'm not quite sure (yet). We've bumped the major version to 3 because we've updated the codebase significantly, but we haven't really broken any plugins.
Thinking out loud, the plugins compatibility story would revolve around the `IPlugin` interface. We must not change it, if we do - we will break plugins. 
If we need to change the contract - we will have to publish a new interface for plugins to implement.

From the plugin manager's perspective you just search for all available plugin and let the user to install what they wish. As long as plugins implement the required interface, we should load them.

/cc: @gitextensions/git-extensions-source thoughts?

**Comment by RussKie** [comment]
At the moment I don't see a value in doing so. 
This makes the manager's logic more complex.

**Comment by maraf** [comment]
OK. So, I should let user install any package with dependency on GE.Plugins of any version, right?

**Comment by RussKie** [comment]
Yes. The worst can happen plugin won't work.

**Comment by maraf** [comment]
OK. In #40 I'm going to remove this version check.
